# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rennen < Formula
  desc "a tool that can run multiple processes in parallel"
  homepage "https://github.com/thejawker/rennen"
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/thejawker/rennen/releases/download/v0.0.4/rennen_Darwin_x86_64.tar.gz"
      sha256 "ec6de4e4ad8b7e8f975c14c1e8f94a08bf5065415b1ee9766c882bdb980304c6"

      def install
        bin.install "ren"
      end
    end
    on_arm do
      url "https://github.com/thejawker/rennen/releases/download/v0.0.4/rennen_Darwin_arm64.tar.gz"
      sha256 "5437acaad1e4683d394991ca10704bf41cff436f0ed1c2b06788c62100ac1e3f"

      def install
        bin.install "ren"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thejawker/rennen/releases/download/v0.0.4/rennen_Linux_x86_64.tar.gz"
        sha256 "67de6fc95b97caa7fea17955a779f4779c0a6d8c17ecf470f9201c11c6051af7"

        def install
          bin.install "ren"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thejawker/rennen/releases/download/v0.0.4/rennen_Linux_arm64.tar.gz"
        sha256 "f5bca323d8cd3403813709b788ec881ee49fd40e957913dd5643e5dec00110fc"

        def install
          bin.install "ren"
        end
      end
    end
  end
end
