# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rennen < Formula
  desc "a tool that can run multiple processes in parallel"
  homepage "https://github.com/thejawker/rennen"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/thejawker/rennen/releases/download/v0.1.0/rennen_Darwin_x86_64.tar.gz"
      sha256 "60b852f06d09eaa939ce07785c999cb5215c9dde2919744d1ccd49ebe3d88232"

      def install
        bin.install "ren"
      end
    end
    on_arm do
      url "https://github.com/thejawker/rennen/releases/download/v0.1.0/rennen_Darwin_arm64.tar.gz"
      sha256 "0bcf079014600de1663017a3a7ceac852325105577917f6dbc21e654580378b1"

      def install
        bin.install "ren"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thejawker/rennen/releases/download/v0.1.0/rennen_Linux_x86_64.tar.gz"
        sha256 "23d274c6799559d2994e5d50b9e4e1885b8a4921c18d2283e30a135743de69bd"

        def install
          bin.install "ren"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thejawker/rennen/releases/download/v0.1.0/rennen_Linux_arm64.tar.gz"
        sha256 "f9717e52ad5c037d19eaac899375db0bd2719909a97f58db298ddf6eb2bc2b32"

        def install
          bin.install "ren"
        end
      end
    end
  end
end
